### ISSUE TITLE
You have got your vaultwarden admin token exposed

### ISSUE THREAD

**Issue by TobiasS1402** [CupricReki/docker-compose#2]
https://github.com/CupricReki/docker-compose/blob/fd7e7fa8a5861001a6c53ca5cb8d59e9f6aa64ba/vaultwarden/docker-compose.yml in this Yaml file you exposed an admin token for your vaultwarden instance. Please be aware

**Comment by TobiasS1402** [comment]
@CupricReki 

> https://github.com/CupricReki/docker-compose/blob/fd7e7fa8a5861001a6c53ca5cb8d59e9f6aa64ba/vaultwarden/docker-compose.yml in this Yaml file you exposed an admin token for your vaultwarden instance. Please be aware

**Comment by CupricReki** [comment]
Thank you very much! Fixed. But I need to find a good way to store secrets. Got any suggestions?

**Comment by TobiasS1402** [comment]
> Thank you very much! Fixed. But I need to find a good way to store secrets. Got any suggestions?

You could take a look at [Mozilla Sops](https://github.com/mozilla/sops), seems to be a possible solution for your needs.
